account/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

code_snippets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from snippets.views import snippet_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('snippets/', include('snippets.urls', namespace='snippets')),
    path('', snippet_list, name="snippets_list"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snippets/urls.py
from django.urls import path
from . import views

app_name = 'snippets'

urlpatterns = [
    path('', views.snippet_list, name='list'),
    path('tag/<slug:tag_slug>/', views.snippet_list, name='snippet_list_by_tag'),
    path('create/', views.snippet_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.snippet_detail, name='detail'),
    path('like/', views.snippet_like, name='like'),
    path('search/', views.snippet_search, name='search'),
]

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(default="404 bio not found", blank=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'Profile of {self.user.username}'

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Email already in use.')
        return data


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError(' Email already in use.')
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'photo']

account/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from snippets.models import Snippet
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib import messages


@login_required
def dashboard(request):
    snippets = Snippet.objects.filter(user=request.user)
    paginator = Paginator(snippets, 8)
    page = request.GET.get('page')
    snippets_only = request.GET.get('snippets_only')
    try:
        snippets = paginator.page(page)
    except PageNotAnInteger:
        snippets = paginator.page(1)
    except EmptyPage:
        if snippets_only:
            return HttpResponse('')
        snippets = paginator.page(paginator.num_pages)
    if snippets_only:
        return render(request, 'snippets/snippet/list_snippets.html', {'section': 'dashboard', 'snippets': snippets})
    return render(request, 'account/dashboard.html', {'section': 'dashboard', 'snippets': snippets})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
        else:
            messages.error(request, 'Error with creating your account', extra_tags='danger')
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile', extra_tags='danger')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/bulma.min.css" %}" rel="stylesheet">
  {% block pygments_css %}
  {% endblock %}
</head>
<body>
  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <span>Code Snippets</span>
      </a>
    </div>

    {% if request.user.is_authenticated %}
    <div class="navbar-menu">
      <div class="navbar-start">
        <a href="{% url 'dashboard' %}" class="navbar-item {% if section == 'dashboard' %}is-active{% endif %}">
          Dashboard
        </a>
  
        <a href="{% url 'snippets:list' %}" class="navbar-item {% if section == 'snippets' %}is-active{% endif %}">
          Snippets
        </a>
      </div>
    </div>
    {% endif %}

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if request.user.is_authenticated %}
          <a href="{% url 'logout' %}" class="button is-light">
            Logout
          </a>
          {% else %}
          <a href="{% url 'login' %}" class="button is-light">
            Log in
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  <section class="section">
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <article class="message is-{{ message.tags }}">
            <div class="message-body">
              {{ message|safe }}
            </div>
          </article>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
  </section>
  <script src="https://kit.fontawesome.com/ffd1a49882.js" crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
  <script>
    const csrftoken = Cookies.get('csrftoken')
    document.addEventListener('DOMContentLoaded', (event) => {
      {% block domready %}
      {% endblock %}
    });
  </script>
</body>
</html>