account/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

code_snippets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from snippets.views import snippet_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('snippets/', include('snippets.urls', namespace='snippets')),
    path('', snippet_list, name="snippets_list"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snippets/urls.py
from django.urls import path
from . import views

app_name = 'snippets'

urlpatterns = [
    path('', views.snippet_list, name='list'),
    path('tag/<slug:tag_slug>/', views.snippet_list, name='snippet_list_by_tag'),
    path('create/', views.snippet_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.snippet_detail, name='detail'),
    path('like/', views.snippet_like, name='like'),
    path('search/', views.snippet_search, name='search'),
]

snippets/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles
from django.utils.text import slugify
from taggit.managers import TaggableManager

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])


class Snippet(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='snippets_created',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(
        max_length=200,
        blank=True
    )
    code = models.TextField()
    linenos = models.BooleanField(default=True)
    language = models.CharField(
        choices=LANGUAGE_CHOICES,
        default='python',
        max_length=100
    )
    style = models.CharField(
        choices=STYLE_CHOICES,
        default='friendly',
        max_length=100
    )
    created = models.DateTimeField(auto_now_add=True)
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='snippets_liked',
        blank=True
    )
    tags = TaggableManager(blank=True)

    class Meta:
        indexes = [
            models.Index(fields=['-created'])
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('snippets:detail', args=[self.pk, self.slug])

snippets/forms.py
from django import forms
from .models import Snippet


class SnippetCreateForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ['title', 'code', 'linenos', 'language', 'style', 'tags']


class SearchForm(forms.Form):
    query = forms.CharField()

snippets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import TrigramSimilarity
from taggit.models import Tag
from .forms import SnippetCreateForm, SearchForm
from .models import Snippet


import redis
from django.conf import settings
# connect to redis
r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)

@login_required
def snippet_create(request):
    if request.method == 'POST':
        form = SnippetCreateForm(data=request.POST)
        if form.is_valid():
            new_snippet = form.save(commit=False)
            #  assign current user to the item
            new_snippet.user = request.user
            new_snippet.save()
            form.save_m2m()
            messages.success(request, 'Snippet added successfully')
            #  redirect to new created item detail view
            return redirect(new_snippet.get_absolute_url())
    else:
        form = SnippetCreateForm()
    return render(request, 'snippets/snippet/create.html', {'section': 'snippets', 'form': form})


def snippet_detail(request, id, slug):
    snippet = get_object_or_404(Snippet, id=id, slug=slug)
    total_views = r.incr(f'snippet:{snippet.id}:views')
    # string: language,style,linenos for custom template tag
    snippet_config = f"{snippet.language},{snippet.style},{snippet.linenos}"
    return render(request, 'snippets/snippet/detail.html', {'section': 'snippets', 'snippet': snippet,
                                                            'snippet_config': snippet_config,
                                                            'total_views': total_views})


@login_required
@require_POST
def snippet_like(request):
    snippet_id = request.POST.get('id')
    action = request.POST.get('action')
    if snippet_id and action:
        try:
            snippet = Snippet.objects.get(id=snippet_id)
            if action == 'like':
                snippet.users_like.add(request.user)
            else:
                snippet.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'error'})


def snippet_list(request, tag_slug=None):
    snippets = Snippet.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        snippets = snippets.filter(tags__in=[tag])
    paginator = Paginator(snippets, 8)
    page = request.GET.get('page')
    snippets_only = request.GET.get('snippets_only')
    try:
        snippets = paginator.page(page)
    except PageNotAnInteger:
        snippets = paginator.page(1)
    except EmptyPage:
        if snippets_only:
            return HttpResponse('')
        snippets = paginator.page(paginator.num_pages)
    if snippets_only:
        return render(request, 'snippets/snippet/list_snippets.html', {'section': 'images', 'snippets': snippets, 'tag': tag})
    return render(request, 'snippets/snippet/list.html', {'section': 'snippets', 'snippets': snippets, 'tag': tag})


def snippet_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Snippet.objects.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request, 'snippets/snippet/search.html', {'form': form, 'query': query, 'results': results})

snippets/templates/snippets/snippet/create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Create Snippet{% endblock %}
{% block content %}
	<h1 class="is-size-1">Create Snippet</h1>
	<hr>
	<form method="post" enctype="multipart/form-data">
		<div class="columns">
			<div class="column is-one-quarter">
				<div class="field">
					<label class="label">Title:</label>
                    <div class="control">
                        {{ form.title|add_class:'input' }}
                    </div>
					<label class="label">Code:</label>
                    <div class="control">
                        {{ form.code|add_class:'textarea' }}
                    </div>
					<label class="label">Line numbers:
						{{ form.linenos|add_class:'checkbox' }}
					</label>
                    <label class="label">Language:</label>
                    <div class="control select">
                        {{ form.language|add_class:'select' }}
                    </div>
					<label class="label">Style:</label>
                    <div class="control select">
                        {{ form.style|add_class:'select' }}
                    </div>
					<label class="label">Tags:</label>
                    <div class="control">
                        {{ form.tags|add_class:'input' }}
						<p class="help">{{ form.tags.help_text|safe }}</p>
                    </div>
				</div>
			</div>
		</div>
		{% csrf_token %}
		<input type="submit" value="Create" class="button">
	</form>
{% endblock %}

snippets/templates/snippets/snippet/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load pygmentize %}
{%block pygments_css %}<style>{% pygments_css %}</style>{% endblock %}
{% block title %}{{ snippet.title }}{% endblock %}
{% block content %}
    {% with total_likes=snippet.users_like.count users_like=snippet.users_like.all %}
    <nav class="level">
        <div class="level-left">
            <p class="level-item has-text-centered title">
                {{ snippet.title }}
            </p>
        </div>
        <div class="level-right">
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Total Views</p>
                    <p class="title">{{ total_views }}</p>
                </div>
            </div>
            
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Like{{ total_likes|pluralize }}</p>
                    <p id="count" class="title">{{ total_likes }}</p>
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
       <div class="sourcecode">
           {{ snippet.code|pygmentize:snippet_config }}  <!-- highlighting -->
       </div>
    </div>
    <br>
    <a href="#" data-id="{{ snippet.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="button is_normal" id="like">
        {% if request.user not in users_like %}
            Like
        {% else %}
            Unlike
        {% endif %}
    </a>
    <hr>
    <h2>Related with:</h2>
    <div class="tags">
        {% for tag in snippet.tags.all %}
        <a href="{% url "snippets:snippet_list_by_tag" tag.slug %}" class="tag is-black">
            {{ tag.name }}
        </a>
        {% endfor %}
    </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    let url = '{% url "snippets:like" %}';
    const options = {
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken},
        mode: 'same-origin'
    };
    document.querySelector('a#like').addEventListener('click', function(e) {
        e.preventDefault();
        const likeButton = this;

        // add request body
        let formData = new FormData();
        formData.append('id', likeButton.dataset.id);
        formData.append('action', likeButton.dataset.action);
        options['body'] = formData;

        //send HTTP request
        fetch(url, options)
        .then(response => response.json())
        .then(data => {
            if (data['status'] === 'ok')
            {
                // toggle button text and data-action
                let previousAction = likeButton.dataset.action;
                let action = '';
                if (previousAction === 'like') {
                    action = 'unlike';
                } else {
                    action = 'like';
                };
                likeButton.dataset.action = action;
                likeButton.innerHTML = action;
                // update like count
                let likeCount = document.querySelector('p#count');
                let totalLikes = parseInt(likeCount.innerHTML);
                likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
            }
        });
    });
{% endblock %}

snippets/templates/snippets/snippet/list.html
{% extends "base.html" %}
{% load i18n %}
{% load pygmentize %}
{% block pygments_css %}<style>{% pygments_css %}</style>{% endblock %}
{% block title %}Snippets{% endblock %}
{% block content %}
    <h1 class="is-size-1">Snippets</h1>
    <hr>
    {% if tag %}
        <h2>Snippets tagged with <b>"{{ tag.name }}"</b></h2>
    {% endif %}
    <div id="snippet-list">
        {% include "snippets/snippet/list_snippets.html" %}
    </div>
{% endblock %}
{% block domready %}
    var page = 1;
    var emptyPage = false;
    var blockRequest = false;
    window.addEventListener('scroll', function(e) {
        var margin = document.body.clientHeight - window.innerHeight - 200;
        if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
            blockRequest = true;
            page += 1;
            fetch('?snippets_only=1&page=' + page)
            .then(response => response.text())
            .then(html => {
                if (html === '') {
                    emptyPage = true;
                }
                else {
                    var snippetList = document.getElementById('snippet-list');
                    snippetList.insertAdjacentHTML('beforeEnd', html);
                    blockRequest = false;
                }
            })
        }
    });
    // Launch scroll event
    const scrollEvent = new Event('scroll');
    window.dispatchEvent(scrollEvent);
{% endblock %}

snippets/templates/snippets/snippet/list_snippets.html
{% load pygmentize %}
{% for snippet in snippets %}
<div class="container">
    {% with total_likes=snippet.users_like.count snippet_config=snippet|get_config %}
    <br>
    <nav class="level">
        <div class="level-left">
            <p class="level-item has-text-centered title">
                <a href="{{ snippet.get_absolute_url }}">
                    {{ snippet.title }}
                </a>
            </p>
        </div>
        <div class="level-right">
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Like{{ total_likes|pluralize }}</p>
                    <p id="count" class="title">{{ total_likes }}</p>
                </div>
            </div>
        </div>

    </nav>
    <div class="container">
       <div class="sourcecode">
           {{ snippet.code|pygmentize:snippet_config }}  <!-- highlighting -->
       </div>
    </div>
    <br>
    <p>Tags:</p>
    <div class="tags">
        {% for tag in snippet.tags.all %}
        <a href="{% url "snippets:snippet_list_by_tag" tag.slug %}" class="tag is-black">
            {{ tag.name }}
        </a>
        {% endfor %}
    </div>
    {% endwith %}
</div>
{% endfor %}

snippets/templates/snippets/snippet/search.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Search{% endblock %}
{% block content %}
  {% if query %}
    <h1 class="is-size-1">Snippets containing "{{ query }}"</h1>
    <hr>
    <h3>
    {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
    </h3>
    {% for snippet in results %}
    <div class="columns">
        <div class="column is-one-quarter">
            <h4>
                <a href="{{ snippet.get_absolute_url }}">
                    {{ snippet.title }}
                </a>
            </h4>
        </div>
    </div>
    {% empty %}
        <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "snippets:search" %}" class="button">Search again</a></p>
  {% else %}
    <h1 class="is-size-1">Search for snippets</h1>
    <form method="get">
        <div class="columns">
			<div class="column is-one-quarter">
				<div class="field">
					<label class="label">Query:</label>
                    <div class="control">
                        {{ form.query|add_class:'input' }}
                    </div>
                </div>
            </div>
        </div>
      <input type="submit" value="Search" class="button">
    </form>
  {% endif %}
{% endblock %}